services:
  - type: web
    name: matomo
    env: docker
    plan: starter
    region: frankfurt
    # Recommended health check endpoint: https://matomo.org/faq/how-to/faq_20278/
    healthCheckPath: /matomo.php
    autoDeploy: false
    disk:
      name: matomo
      mountPath: /var/www/html
      sizeGB: 20
    envVars:
      - key: MATOMO_DATABASE_HOST
        fromService:
          name: mysql
          type: web
          property: host
      - key: MATOMO_DATABASE_USERNAME
        fromService:
          name: mysql
          type: web
          envVarKey: MYSQL_USER
      - key: MATOMO_DATABASE_PASSWORD
        fromService:
          name: mysql
          type: web
          envVarKey: MYSQL_PASSWORD
      - key: MATOMO_DATABASE_DBNAME
        fromService:
          name: mysql
          type: web
          envVarKey: MYSQL_DATABASE

